groups:
  Admin:
  - 1
  - 2
  - 3
  default:
  - 3
  - 7
  Member:
  - 7
commands:
    rules:
      id: 7
      message: 'Here are the rules'
      permission: 'test.permission.or.none'
settings:
  only-on-first-join: true
  cache-size: 100
shop:
  need-books: true
selling:
  need-books: true
sql:
  mysql: false
  host: 'localhost'
  port: 3306
  user: 'minecraft'
  password: 'password'
  database: 'copybooks'